@startuml
title Gravity Social Care Benefit Eligibility Workflow

participant Patient
participant "Provider/CBO" as Provider
participant Payer
participant HRSNProvider

note across: Patient completes a social risk assessment instrument during or prior to encounter
'Provider -> Patient: Screening Questionnaire
'Patient -> Provider: Screening QuestionnaireResponse
|||
note over Provider, Patient: Patient arrives for appointment
Provider -> Provider: Confirm social risk and mutually define social need
group Social Care Benefit Eligibility Determination (CRD/CDS Hooks)
  autonumber 1 "<font color=red size=18>"
  Provider -> Payer: Request eligibility check
  autonumber stop
  activate Payer

  Payer <--> Provider: Request additional information

  autonumber 2 "<font color=red size=18>"
  Payer -> Provider: Send eligibility determination
  autonumber stop
  deactivate Payer
end
Provider -> Provider: View information on available benefits

group Social Care Referral
  Provider -> HRSNProvider: Referral
  HRSNProvider -> Patient: Provide service
  HRSNProvider -> Provider: Notify that services provided
end
@enduml
